set nocompatible              " be iMproved, required
filetype off                  " required

"-------------------------------------------------------------------------------------------------"
"                                               PLUGINS
"-------------------------------------------------------------------------------------------------"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Support file:line
Plugin 'bogado/file-line'

" Version control
Plugin 'tpope/vim-fugitive'
Plugin 'mhinz/vim-signify'

" File explorer
 Plugin 'preservim/nerdtree'

" File layout
Plugin 'preservim/tagbar'

" Linux kernel coding style
Plugin 'gregkh/kernel-coding-style'

" Rust support
" Plugin 'rust-lang/rust.vim'

" Enhance
Plugin 'tpope/vim-surround'

" Completion
Plugin 'raimondi/delimitmate'

" LangServ will this work one day ?
"Plugin 'dense-analysis/ale'

" Color schemes
Plugin 'baycomb'
Plugin 'bdesham/biogoo'
Plugin 'donbass.vim'
Plugin 'fog-colorscheme'
Plugin 'jhlight.vim'
Plugin 'oceanblack.vim'
Plugin 'Sift'
Plugin 'smp'
Plugin 'tango-morning.vim'
Plugin 'Transparent'
Plugin 'vcbc.vim'
Plugin 'xemacs-colorscheme'
Plugin 'dracula/vim'

" ??? what the fuck is this ???
" Plugin 'junegunn/goyo.vim'

" Show color from hex
" /!\ Only use it manually /!\
"Plugin 'lilydjwg/colorizer'

""""""""""""""""""""""""""""""""""""""""""""""""""""
" Checkout https://vimawesome.com for more plugins
""""""""""""""""""""""""""""""""""""""""""""""""""""

" All of your Plugins must be added before the following line
call vundle#end()            " required

" Re-enable filetype specific plugin and indent
filetype plugin indent on    " required

"-------------------------------------------------------------------------------------------------"

" Global settings
set background=dark
syntax on	" Enables the syntax highlighting
set mouse=a	" Enable mouse scrolling
set ignorecase smartcase	" Improve search
set autoindent smartindent	" Improve indentation
set hlsearch			" Hightlight search

" Highlight tabs and trailing whitespaces
set listchars=tab:»\ ,trail:·
set list

" Colorscheme differs between GUI and CLI
if has("gui_running")
	colors baycomb
	set guifont=JetBrains
else
	" Set consistent bgcolor with Xres file before loading the colorscheme
	let g:dracula_colorterm = 0
	colors baycomb
endif

" Handle GUI specific options
if has("gui_running")
	set guioptions -=T  " Removes the toolbar
	"set guioptions -=m  " Removes the menu
endif

" NERDTree plugin config
nmap <F4> :NERDTreeToggle<CR>	" Map F4 to NERDTree
let g:NERDTreeMouseMode = 1	" Single clic to open

" Tagbar plugin settings
nmap <F3> :TagbarToggle<CR>	" Map F3 to Tagbar
"let g:tagbar_sort = 0		" Sort tags according to source file order

" Colorizer plugin settings
let g:colorizer_startup = 0	" Don't enable colorizer at startup

" Apply local config for weeklies
autocmd BufRead,BufNewFile ~/Documents/m33tdcid/* setlocal textwidth=70 filetype=rst
autocmd BufRead,BufNewFile ~/Documents/os-team/* setlocal textwidth=70 filetype=rst
